---
- hosts: workstation
  vars_files:
    - vars/main.yml
  tasks:
    - name: Install packages available in Ubuntu repository
      ansible.builtin.apt:
        name: "{{ apt_packages }}"
        update_cache: yes
        state: present

    - name: Install snap packages
      community.general.snap:
        name: "{{ snap_packages }}"
